version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres
    hostname: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '4dm1n$1Z3'
      POSTGRES_DB: vehicle_tracking
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS='4dm1n$1Z3'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/

volumes:
  postgres_data:
  rabbitmq_data:


